export const MONGO_DATABASE_NAME = 'real-vision';

export enum Collection {
    ADMINS = 'admins',
    COMPUTERS = 'computers',
    PRODUCTS = 'products',
    BRANDS = 'brands',
    LEADS = 'leads',
    POSTS = 'posts',
    GAMES = 'games',
    ISSUES = 'issues',
    PROJECTS = 'projects',
    PROGRAMS = 'programs',
    COMPUTERS_CATEGORY= "computer_categories",
    PRODUCTS_CATEGORIES= "product_categories",
    COMPUTERS_BUILD="computers_build",
    DESKS= "desks",
    PAYMENTS= "payments",
    CLIENTS = 'clients',
    SERVICES = 'services',
    EVENTS = 'events',
    PAGES = 'pages',
    QUOTES = 'quotes',
    SELLS = 'sells',
    EXPENSES = 'expenses',
    PAYSHEETS = 'paysheets',
    COSTS = 'costs',
    PARTNERS = 'partners',
}
